class Packet(object):
    CODE_INVALID = 0
    CODE_ACCESS_REQUEST = 1
    CODE_ACCESS_ACCEPT = 2
    CODE_ACCESS_REJECT = 3
    CODE_ACCOUNT_REQUEST = 4
    CODE_ACCOUNT_RESPONSE = 5
    CODE_ACCESS_CHALLENGE = 11
    CODE_DISCONNECT_REQUEST = 40
    CODE_DISCONNECT_ACK = 41
    CODE_DISCONNECT_NAK = 42
    CODE_COA_REQUEST = 43
    CODE_COA_ACK = 44
    CODE_COA_NAK = 45

    # EAP Code
    CODE_EAP_REQUEST = 1
    CODE_EAP_RESPONSE = 2
    CODE_EAP_SUCCESS = 3
    CODE_EAP_FAILURE = 4

    # EAP Type
    TYPE_EAP_IDENTITY = 1
    TYPE_EAP_NOTIFICATION = 2
    TYPE_EAP_NAK = 3
    TYPE_EAP_GTC = 6
    TYPE_EAP_SIM = 18
    TYPE_EAP_AKA = 23
    TYPE_EAP_PEAP = 25
    TYPE_EAP_MSCHAPV2 = 26
